import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
import MoviveCard from '../components/MovieCard';
import useFetchMovies from '../hooks/useFetchMovies';

export default function Home() {
  const [page, setPage] = useState(1);
  const { movies, isError, isLoading: isLoadingMovies } = useFetchMovies(page);

  const handleScroll = (e) => {
    let element = e.target;
    const bottom =
      Math.round(element.scrollHeight - element.scrollTop) ===
      element.clientHeight;
    console.log('=============');
    console.log(Math.round(element.scrollHeight - element.scrollTop));
    console.log(element.clientHeight);
    if (bottom) {
      console.log('inin');
      setPage((state) => state + 1);
    }
  };

  if (isLoadingMovies) {
    return 'LOADING';
  }

  return (
    <div
      className='bg-white sm:py-8 lg:py-12'
      style={{
        height: '100vh',
        width: '100%',
        overflow: 'auto',
      }}
      onScroll={handleScroll}
    >
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
        {movies.map((movie) => {
          return (
            <MoviveCard
              key={movie.id}
              title={movie.title}
              overview={movie.overview}
              image={movie.poster_path}
            />
          );
        })}
      </div>
    </div>
  );
}
